# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    cache: 
        psr6_app_cache:
            psr6: 
                service: cache.flysystem.psr6
    adapters:
        upload_adapter:
            awss3v3:
                client: Aws\S3\S3Client
                bucket: '%env(AWS_S3_BUCKET)%'
    filesystems:
        upload_filesystem:
            adapter: upload_adapter
            # alias: League\Flysystem\Filesystem
        cached_upload_filesystem:
            adapter: upload_adapter
            cache: psr6_app_cache
            # alias: League\Flysystem\Filesystem
