# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        upload_adapter:
            local:
                directory: '%kernel.project_dir%/public/%upload_dir_name%'
    filesystems:
        upload_filesystem:
            adapter: upload_adapter
            # alias: League\Flysystem\Filesystem
